In [69]:
import pandas as pd
import sys
import numpy as np
X_train = pd.read_csv('Xtrain.csv')

In [70]:
X_train

,LOC101929698,EIF2B5,KBTBD3,CLVS1,IL10RA,LINGO3,CAPN2,CDKL1,GTF3A,MICAL1,...,STK38,ZSCAN18,ALDH1A3,NARS,MYNN,LOC101928062,HSPA8,GLE1,KCTD19,RAB24
0,6.896541,2.799818,5.956728,6.886279,3.978908,7.728197,3.306650,7.832358,7.757861,7.040414,...,3.591389,4.644093,-0.801474,3.654349,-0.447319,3.002883,5.846178,4.999578,1.189316,4.288712
1,7.663616,1.829348,5.916302,7.014029,4.010571,7.882492,4.425787,7.340918,7.711562,7.381636,...,2.423283,4.458377,1.890772,2.594808,5.717222,3.453497,5.402420,4.452666,3.039020,4.777298
2,6.800005,2.809166,6.431447,7.118486,3.792339,7.200910,4.870456,7.445268,7.305027,6.273474,...,3.481930,3.619848,2.735097,4.472817,4.294737,3.630775,5.451112,3.904717,3.640731,3.697474
3,6.742322,1.816235,6.935131,7.200237,4.631528,8.302534,4.911997,7.931061,7.429479,7.509660,...,4.112838,2.954344,2.744293,2.580431,4.231591,2.034389,5.103424,5.228291,4.728575,4.574527
4,7.627112,2.787321,6.648940,6.966904,5.755796,7.754693,5.083538,6.936141,8.228015,7.139592,...,0.433757,3.660001,3.564265,2.796353,3.613882,5.015744,5.134560,5.560713,3.244187,4.675465
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,7.426399,4.529685,5.750212,6.628467,2.424641,7.451437,5.533676,8.150899,8.419200,7.701183,...,4.255721,4.585225,4.945020,2.713873,5.092608,4.531906,5.396172,4.580560,3.158085,3.938898
113,7.368819,2.394112,5.928407,6.069539,-0.568457,8.860285,5.115251,8.472141,7.533569,7.633832,...,3.243972,5.985547,3.468226,2.094660,3.877758,2.624752,4.189259,4.637529,4.588688,4.361676
114,7.246303,-0.357814,6.843400,6.653924,0.291236,8.323299,5.274714,8.111245,7.413504,7.932020,...,4.679292,5.475068,2.518180,3.816371,2.010046,2.634866,2.989655,5.290756,3.123981,4.210307
115,7.420143,3.873969,5.400032,6.998013,3.717765,7.933215,3.732008,7.710265,8.210689,7.407552,...,3.385323,3.772300,1.648493,2.842117,2.058024,1.953351,4.662149,4.930241,-1.141905,2.304567
116,7.527232,3.151717,6.832992,6.740451,4.664741,7.971511,5.377226,7.502193,7.963487,7.603124,...,4.580620,4.067460,3.077499,4.337550,2.044272,4.658740,5.534662,4.991175,3.688985,4.584849

In [45]:
X_train.to_csv('a.csv',index = False)

In [46]:
a =  pd.read_csv('a.csv')

In [47]:
a

,LOC101929698,EIF2B5,KBTBD3,CLVS1,IL10RA,LINGO3,CAPN2,CDKL1,GTF3A,MICAL1,...,STK38,ZSCAN18,ALDH1A3,NARS,MYNN,LOC101928062,HSPA8,GLE1,KCTD19,RAB24
0,NaN,2.799818,5.956728,6.886279,3.978908,7.728197,3.306650,7.832358,7.757861,7.040414,...,3.591389,4.644093,-0.801474,3.654349,-0.447319,3.002883,5.846178,4.999578,1.189316,4.288712
1,7.663616,1.829348,5.916302,7.014029,4.010571,7.882492,4.425787,7.340918,7.711562,7.381636,...,2.423283,4.458377,1.890772,2.594808,5.717222,3.453497,5.402420,4.452666,3.039020,4.777298
2,6.800005,2.809166,6.431447,7.118486,3.792339,7.200910,4.870456,7.445268,7.305027,6.273474,...,3.481930,3.619848,2.735097,4.472817,4.294737,3.630775,5.451112,3.904717,3.640731,3.697474
3,6.742322,1.816235,6.935131,7.200237,4.631528,8.302534,4.911997,7.931061,7.429479,7.509660,...,4.112838,2.954344,2.744293,2.580431,4.231591,2.034389,5.103424,5.228291,4.728575,4.574527
4,7.627112,2.787321,6.648940,6.966904,5.755796,7.754693,5.083538,6.936141,8.228015,7.139592,...,0.433757,3.660001,3.564265,2.796353,3.613882,5.015744,5.134560,5.560713,3.244187,4.675465
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,7.426399,4.529685,5.750212,6.628467,2.424641,7.451437,5.533676,8.150899,8.419200,7.701183,...,4.255721,4.585225,4.945020,2.713873,5.092608,4.531906,5.396172,4.580560,3.158085,3.938898
113,7.368819,2.394112,5.928407,6.069539,-0.568457,8.860285,5.115251,8.472141,7.533569,7.633832,...,3.243972,5.985547,3.468226,2.094660,3.877758,2.624752,4.189259,4.637529,4.588688,4.361676
114,7.246303,-0.357814,6.843400,6.653924,0.291236,8.323299,5.274714,8.111245,7.413504,7.932020,...,4.679292,5.475068,2.518180,3.816371,2.010046,2.634866,2.989655,5.290756,3.123981,4.210307
115,7.420143,3.873969,5.400032,6.998013,3.717765,7.933215,3.732008,7.710265,8.210689,7.407552,...,3.385323,3.772300,1.648493,2.842117,2.058024,1.953351,4.662149,4.930241,-1.141905,2.304567
116,7.527232,3.151717,6.832992,6.740451,4.664741,7.971511,5.377226,7.502193,7.963487,7.603124,...,4.580620,4.067460,3.077499,4.337550,2.044272,4.658740,5.534662,4.991175,3.688985,4.584849

In [48]:
import random

In [63]:
random.randint(1,3)

2

In [64]:
from fancyimpute import KNN, NuclearNormMinimization, SoftImpute, IterativeImputer, BiScaler

Using TensorFlow backend.

In [65]:
X_train_incomplete= pd.read_csv('Xtrain_miss_10.csv')

In [78]:
X_train_incomplete

,LOC101929698,EIF2B5,KBTBD3,CLVS1,IL10RA,LINGO3,CAPN2,CDKL1,GTF3A,MICAL1,...,STK38,ZSCAN18,ALDH1A3,NARS,MYNN,LOC101928062,HSPA8,GLE1,KCTD19,RAB24
0,6.896541,2.799818,5.956728,6.886279,3.978908,NaN,3.306650,7.832358,7.757861,NaN,...,3.591389,4.644093,-0.801474,3.654349,-0.447319,3.002883,5.846178,4.999578,1.189316,4.288712
1,NaN,1.829348,5.916302,7.014029,4.010571,7.882492,4.425787,7.340918,7.711562,7.381636,...,2.423283,4.458377,1.890772,2.594808,5.717222,3.453497,5.402420,4.452666,3.039020,4.777298
2,6.800005,NaN,6.431447,7.118486,3.792339,7.200910,4.870456,7.445268,NaN,6.273474,...,3.481930,3.619848,2.735097,4.472817,4.294737,3.630775,5.451112,3.904717,3.640731,3.697474
3,6.742322,NaN,6.935131,7.200237,4.631528,8.302534,4.911997,7.931061,7.429479,7.509660,...,4.112838,2.954344,2.744293,2.580431,4.231591,2.034389,5.103424,5.228291,4.728575,4.574527
4,7.627112,2.787321,6.648940,6.966904,5.755796,NaN,5.083538,6.936141,NaN,7.139592,...,0.433757,3.660001,3.564265,2.796353,3.613882,5.015744,5.134560,5.560713,3.244187,4.675465
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,7.426399,4.529685,5.750212,6.628467,2.424641,7.451437,5.533676,8.150899,NaN,7.701183,...,4.255721,NaN,4.945020,2.713873,NaN,4.531906,5.396172,4.580560,3.158085,3.938898
113,7.368819,2.394112,5.928407,6.069539,-0.568457,8.860285,NaN,NaN,7.533569,7.633832,...,3.243972,5.985547,3.468226,2.094660,3.877758,2.624752,4.189259,4.637529,4.588688,4.361676
114,7.246303,-0.357814,NaN,6.653924,0.291236,8.323299,5.274714,8.111245,7.413504,7.932020,...,4.679292,5.475068,2.518180,3.816371,2.010046,2.634866,2.989655,5.290756,3.123981,4.210307
115,NaN,3.873969,5.400032,6.998013,3.717765,7.933215,3.732008,7.710265,8.210689,7.407552,...,3.385323,NaN,NaN,NaN,2.058024,1.953351,NaN,4.930241,-1.141905,2.304567
116,7.527232,3.151717,6.832992,NaN,4.664741,7.971511,5.377226,7.502193,7.963487,7.603124,...,4.580620,4.067460,3.077499,4.337550,2.044272,4.658740,5.534662,4.991175,3.688985,4.584849

In [79]:
X_filled_knn = KNN(k=3).fit_transform(X_train_incomplete)

Imputing row 1/117 with 563 missing, elapsed time: 0.674
Imputing row 101/117 with 571 missing, elapsed time: 1.321

In [75]:
pd.DataFrame(X_filled_knn).to_csv('Xtrain_KNN_10.csv',index = False)

In [82]:
from fancyimpute import MICE

ImportError: cannot import name 'MICE' from 'fancyimpute' (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fancyimpute/__init__.py)

In [80]:
X_filled_ISVD = IterativeSVD().fit_transform(X_train_incomplete)

[IterativeSVD] Iter 1: observed MAE=0.976160
[IterativeSVD] Iter 2: observed MAE=0.742360
[IterativeSVD] Iter 3: observed MAE=0.706772
[IterativeSVD] Iter 4: observed MAE=0.675929
[IterativeSVD] Iter 5: observed MAE=0.663684
[IterativeSVD] Iter 6: observed MAE=0.663490
[IterativeSVD] Iter 7: observed MAE=0.663452
[IterativeSVD] Iter 8: observed MAE=0.663404
[IterativeSVD] Iter 9: observed MAE=0.663347
[IterativeSVD] Iter 10: observed MAE=0.663288
[IterativeSVD] Iter 11: observed MAE=0.663230
[IterativeSVD] Iter 12: observed MAE=0.663176

In [76]:
pd.DataFrame(X_filled_ISVD).to_csv('Xtrain_ISVD_10.csv',index = False)

In [88]:
from impyute import mice,em,mean

In [ ]:
X_filled_ISVD =  IterativeSVD().fit_transform(X_train_incomplete)